// src/config/worlds.config.js
// 10 topic-themed worlds for ProgressionQuest: Grade 7 Arithmetic Sequences
// Defined per PRD §9 & TRD §4.1

export const WORLDS = [
  {
    id: 0,
    name: "Reading the Telemetry",
    emoji: "📡",
    accent: "var(--world-0)",
    description: "Define an AP; identify first term a and common difference d",
    conceptFocus: "define-identify-ap",
    boss: { name: "The Static Signal", emoji: "📡", reward: "Telemetry Badge" },
  },
  {
    id: 1,
    name: "Mission Integrity Check",
    emoji: "⚠️",
    accent: "var(--world-1)",
    description: "Verify a sequence is arithmetic by checking every gap",
    conceptFocus: "verify-arithmetic-sequence",
    boss: { name: "The Rogue Reading", emoji: "⚠️", reward: "Integrity Badge" },
  },
  {
    id: 2,
    name: "The Trajectory Formula",
    emoji: "🧮",
    accent: "var(--world-2)",
    description: "Apply Tn = a + (n-1)d to find a specified term",
    conceptFocus: "general-term-formula",
    boss: { name: "The Formula Firewall", emoji: "🧮", reward: "Trajectory Badge" },
  },
  {
    id: 3,
    name: "Solve for the Unknown Stage",
    emoji: "❓",
    accent: "var(--world-3)",
    description: "Solve for a, d, or n given partial AP information",
    conceptFocus: "solve-for-a-d-n",
    boss: { name: "The Missing Variable", emoji: "❓", reward: "Solver's Badge" },
  },
  {
    id: 4,
    name: "Filling the Gaps",
    emoji: "🕳️",
    accent: "var(--world-4)",
    description: "Interpolate missing terms given two known non-adjacent terms",
    conceptFocus: "interpolate-missing-terms",
    boss: { name: "The Data Gap", emoji: "🕳️", reward: "Gap-Filler Badge" },
  },
  {
    id: 5,
    name: "Extra Checkpoints",
    emoji: "📍",
    accent: "var(--world-5)",
    description: "Insert arithmetic mean(s) between two given numbers",
    conceptFocus: "arithmetic-means",
    boss: { name: "The Checkpoint Guardian", emoji: "📍", reward: "Navigator Badge" },
  },
  {
    id: 6,
    name: "Is It on the Flight Path?",
    emoji: "🛰️",
    accent: "var(--world-6)",
    description: "Determine whether a number is a term of the sequence",
    conceptFocus: "test-membership",
    boss: { name: "The Flight Path Phantom", emoji: "🛰️", reward: "Tracker Badge" },
  },
  {
    id: 7,
    name: "Countdown to Launch",
    emoji: "⏱️",
    accent: "var(--world-7)",
    description: "Full multi-step real-world AP scenario",
    conceptFocus: "applied-multi-step-ap",
    boss: { name: "The Countdown Glitch", emoji: "⏱️", reward: "Launch Badge" },
  },
  {
    id: 8,
    name: "Total Burn",
    emoji: "⛽",
    accent: "var(--world-8)",
    description: "Find the sum of the first n terms (flagged extension)",
    conceptFocus: "sum-of-n-terms",
    boss: { name: "The Fuel Gauge Dragon", emoji: "⛽", reward: "Engineer's Badge" },
    isExtension: true,
  },
  {
    id: 9,
    name: "Mission Control: Final Countdown",
    emoji: "🚀",
    accent: "var(--world-9)",
    description: "Mixed review of every concept above; hardest boss",
    conceptFocus: "mixed-review",
    boss: { name: "Mission Commander Vega", emoji: "🚀", reward: "Chief Cadet Trophy" },
  },
];
